org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=cobblemon-torchmaster-fix
mod_id=cobblemon_torchmaster_fix
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon Torchmaster Fix
mod_description=Allows Torchmaster to prevent Cobblemon from spawning in areas where it is not allowed to spawn.
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/cobblemon-torchmaster-fix/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/cobblemon-torchmaster-fix
git_url=github.com/Matthiesen-dev/cobblemon-torchmaster-fix
modrinth_url=https://modrinth.com/mod/cobblemon-torchmaster-fix

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1